(function () {
  'use strict';

  var STRINGS = {
    en: {
      // === SHARED NAV / FOOTER ===
      nav_how_it_works: 'How it works',
      nav_curriculum: 'Curriculum',
      nav_pricing: 'Pricing',
      nav_signout: 'Sign out',
      nav_signin: 'Sign in',
      nav_get_started: 'Get Started',
      footer_copy: '\u00A9 2026 Nuvo Math \u00B7 nuvostudio.club',
      footer_tagline: 'Math practice that actually teaches. Guided step-by-step practice and live tutoring.',
      loading_just_moment: 'Just a moment!',

      // === login.html ===
      login_label: 'Student Login',
      login_heading: 'Welcome back',
      login_sub: 'Enter your student ID to continue',
      login_id_label: 'Student ID',
      login_id_placeholder: 'e.g. sofia',
      login_submit: 'Sign in \u2192',
      login_error_notfound: 'Student ID not found \u2014 check with your teacher',
      login_no_account: "Don't have an account?",
      login_trial_link: 'Request enrollment \u2192',
      login_signing_in: 'Signing in\u2026',
      login_error_generic: 'Something went wrong. Please try again.',
      login_error_network: 'Network error. Check your connection and try again.',

      // === home.html ===
      welcome_back: 'Welcome back,',
      curriculum_loading: 'Loading your curriculum\u2026',
      section_your_curriculum: 'Your curriculum',
      unit_label: 'Unit',
      level_label: 'Level',
      home_help_link: 'Need help? Ask Ronel',
      home_session_note: 'Your next session: check WhatsApp for scheduling',
      home_offline: 'Offline \u2014 check your connection',
      trial_expired_heading: 'Your access has ended',
      trial_expired_body: 'Submit the enrollment form to choose a plan and arrange payment. We usually reply within a few hours with next steps.',
      trial_expired_note: 'Questions? Email tutor@nuvostudio.club or WhatsApp 6014-1676.',
      trial_practice_btn: 'Enrollment form \u2192',
      trial_tutoring_btn: 'WhatsApp us \u2192',

      // === lesson.html ===
      back_to_curriculum: '\u2190 Back to curriculum',
      loading_lesson_h2: 'Loading lesson\u2026',
      error_missing_params_h2: 'Missing lesson parameters',
      error_missing_params_p: 'This page requires <code>curriculum</code>, <code>unit</code>, and <code>stage</code> URL parameters.',
      error_lesson_not_found_h2: 'Lesson not found',
      error_load_failed_h2: "Couldn\u2019t load lesson",
      error_load_failed_p: 'Check your internet connection and try refreshing.',
      phase_intro: 'Intro',
      phase_concepts: 'Concepts',
      phase_example: 'Example',
      phase_practice: 'Practice',
      phase_test: 'Test',
      cover_begin_btn: 'Begin Lesson \u2192',
      concepts_card_title: 'Key Concepts',
      concepts_no_rules: 'No rules listed.',
      concepts_next_btn: 'Got it \u2014 show me an example \u2192',
      concept_tab_written: 'Written',
      concept_tab_visual: 'Visual',
      concept_tab_formula: 'Formula',
      concept_tab_voice: 'Voice',
      concept_visual_step: 'Idea',
      formula_no_items: 'No formulas listed yet.',
      voice_listen_btn: 'Listen',
      voice_stop_btn: 'Stop',
      voice_no_text: 'No narration available yet.',
      example_card_title: 'Worked Example',
      example_tab_symbolic: 'Symbolic',
      example_tab_visual: 'Visual',
      example_visual_empty: 'Visual representation will appear here.',
      example_narration_init: 'Follow along \u2014 tap the button below to step through the example.',
      example_btn_previous: '\u2190 Previous',
      example_btn_show_step_n: 'Show step {n}',
      example_btn_goto_practice: 'Go to Practice \u2192',
      example_btn_try_yourself: 'Try it yourself \u2192',
      practice_tag: 'Practice',
      practice_subtitle: 'Work through these practice problems. Hints are available.',
      test_tag: 'Level Test',
      test_subtitle: 'Answer all questions. No hints this time!',
      result_complete: 'Complete!',
      result_level_complete: 'Level complete!',
      result_great_work: 'Great work \u2014 the next level is now unlocked.',
      result_score_correct: 'You got {score} of {total} correct.',
      result_back_btn: 'Back to curriculum \u2192',
      result_fail_h2: 'Keep Practicing!',
      result_fail_review: 'Review the example again and try the test once more.',
      result_fail_btn: 'Review example \u2192',

      // === dashboard.html ===
      loading_problems_h2: 'Loading your problems\u2026',
      error_no_student_h2: 'No student ID found',
      error_no_student_p: "Make sure you opened the right link. Ask your teacher if you're not sure!",
      error_student_notfound_h2: 'Student not found',
      error_student_notfound_p: "We couldn\u2019t find a student with the ID {id}. Check your link or ask your teacher.",
      error_load_problems_h2: "Couldn\u2019t load your problems",
      error_load_problems_p: 'Check your internet connection and try refreshing the page.',
      dashboard_hi: 'Hi,',
      dashboard_problems_label: 'Problems completed',
      dashboard_no_problems: 'No problems assigned yet.',
      dashboard_all_done: "Amazing \u2014 you've finished everything! \uD83C\uDF89",
      dashboard_get_started: 'Tap a problem below to get started!',
      dashboard_keep_going: 'Keep going \u2014 {n} left to go!',
      dashboard_completed: 'Completed',
      dashboard_not_started: 'Not started',
      dashboard_practice_again: 'Practice again \u2192',
      dashboard_your_problems: 'Your Problems',
      dashboard_all_done_banner: "You've finished all your problems \u2014 brilliant work!",
      dashboard_generating: 'Generating\u2026',
      dashboard_try_again: 'Try again',

      // === teacher.html ===
      teacher_login_h2: 'Teacher Login',
      teacher_login_p: 'Enter your teacher password to continue.',
      teacher_password_placeholder: 'Password',
      teacher_unlock_btn: 'Unlock',
      teacher_dashboard_h1: 'Teacher Dashboard',
      teacher_subtitle: 'Nuvo Studio',
      teacher_tab_students: 'Students & Homework',
      teacher_tab_problems: 'Problem Bank',
      teacher_all_students: 'ALL STUDENTS',
      teacher_loading: 'Loading\u2026',
      teacher_new_student_btn: '+ New Student',
      teacher_select_student: 'Select a student from the list to begin.',
      teacher_student_profile: 'Student Profile',
      teacher_edit_btn: 'Edit \u270F\uFE0F',
      teacher_edit_profile: 'Edit Profile',
      teacher_label_name: 'Name',
      teacher_label_student_id: 'Student ID',
      teacher_label_curriculum: 'Curriculum',
      teacher_label_grade: 'Grade / Stage',
      teacher_label_trial: 'Trial expiry',
      teacher_optional: '(optional)',
      teacher_auto_generated: '(auto-generated)',
      teacher_calc_hint: '(tap Question or Answer first)',
      teacher_save_btn: 'Save',
      teacher_cancel_btn: 'Cancel',
      teacher_new_student_title: 'New Student',
      teacher_create_btn: 'Create Student',
      teacher_homework_title: 'Homework',
      teacher_homework_note: 'Assigned problems appear on the student\u2019s home screen under \u201CYour homework\u201D',
      teacher_no_homework: 'No homework assigned yet',
      teacher_assign_label: 'Assign from problem bank',
      teacher_problem_id_placeholder: 'Problem ID',
      teacher_assign_btn: 'Assign',
      teacher_oneoff_heading: 'Or create a one-off problem',
      teacher_question_label: 'Question',
      teacher_word_desc: 'Word description',
      teacher_answer_label: 'Answer',
      teacher_expected_answer: 'Expected answer',
      teacher_add_assign_btn: 'Add & assign',
      teacher_student_link_label: 'Student link:',
      teacher_copy_link_btn: 'Copy link',
      teacher_problems_title: 'Problems',
      teacher_add_to_bank_title: 'Add to Bank',
      teacher_unit_label: 'Unit',
      teacher_level_label: 'Level',
      teacher_problem_type_label: 'Problem Type',
      teacher_math_type_label: 'Math Type',
      teacher_calc_label: 'Calculator',
      teacher_hint_label_1: 'Hint 1',
      teacher_hint_label_2: 'Hint 2',
      teacher_hint_label_3: 'Hint 3',
      teacher_add_hints: 'Add hints \u25BE',
      teacher_hide_hints: 'Add hints \u25B4',
      teacher_pid_label: 'Problem ID',
      teacher_save_to_bank_btn: 'Save to bank',
      teacher_saved_to_bank: 'Saved to bank \u2713',
      teacher_no_problems: 'No problems yet.',
      teacher_pf_curriculum_grade: 'Curriculum & Grade',
      teacher_trial_expired_label: 'Expired',
      teacher_trial_days_left: '{n}d left',
      teacher_auth_error_empty: 'Please enter a password.',
      teacher_id_required: 'ID and name are required.',
      teacher_saving: 'Saving\u2026',
      teacher_creating: 'Creating\u2026',
      teacher_steps_show: 'Steps \u25BE',
      teacher_steps_hide: 'Steps \u25B4',
      teacher_no_attempts: 'No attempts yet.',
      teacher_loading_logs: 'Loading\u2026',
      teacher_failed_logs: 'Failed to load logs.',
      teacher_toast_select_student: 'Select a student first.',
      teacher_toast_enter_pid: 'Enter a problem ID.',
      teacher_toast_problem_notfound: 'Problem \u201C{pid}\u201D not found in bank.',
      teacher_toast_already_assigned: 'Already assigned.',
      teacher_toast_assigned: 'Problem assigned.',
      teacher_toast_enter_qna: 'Enter question and answer.',
      teacher_toast_oneoff_assigned: 'One-off problem assigned.',
      teacher_toast_link_copied: 'Link copied!',
      teacher_toast_fill_required: 'Please fill in all required fields.',
      teacher_toast_wrong_password: 'Wrong password.',
      teacher_toast_failed_save: 'Failed to save. Check connection.',
      teacher_toast_failed_create: 'Creation failed. Check connection.',
      teacher_toast_failed_homework: 'Failed to save homework. Check connection.',
      teacher_toast_failed_student: 'Failed to load student data.',
      teacher_toast_failed_students: 'Could not load students.',
      teacher_toast_failed_problems: 'Could not load problems.',
      hw_tag_diagnostic: 'Diagnostic',
      hw_tag_test: 'Test',
      hw_tag_oneoff: 'One-off',
      hw_tag_practice: 'Practice',
      filter_all: 'All',

      // === index.html ===
      hero_eyebrow: 'Guided math + live tutoring',
      hero_headline: 'Prepare for the UTP exam.',
      hero_sub: '<strong>Practice anytime.</strong> Step-by-step guided practice with hints, examples, and immediate feedback \u2014 so you arrive at the exam with confidence.',
      hero_cta_primary: 'Start Practicing',
      hero_cta_secondary: 'See How It Works',
      hero_signin_note: 'Already enrolled?',
      hero_signin_link: 'Sign in \u2192',
      hero_demo_aria: 'Animated preview: guided practice with a hint and instant feedback',
      hero_demo_title: 'Guided practice',
      hero_demo_prompt: 'Solve for x: 2x + 3 = 11',
      hero_demo_step_label: 'Step 1 of 3',
      hero_demo_step_q: 'What should you do first to isolate the term with x?',
      hero_demo_hint_tag: 'Hint',
      hero_demo_hint_text: 'Subtract 3 from both sides.',
      hero_demo_feedback: 'Nice \u2014 that keeps the equation balanced.',
      hero_engine_aria: 'Animated preview: each line you enter is checked before you continue',
      hero_engine_count: '1/1',
      hero_engine_meta: 'Problem 1 of 1 \u00B7 Simplify',
      hero_engine_expr: '3x \u2212 2y + 6x + 9y',
      hero_engine_line1: '(3x + 6x) + (\u22122y + 9y)',
      hero_engine_line2: '9x + (\u22122y + 9y)',
      hero_engine_nudge: 'Correct value, but try to simplify or factor further!',
      hero_engine_placeholder: 'Type or tap buttons to enter your answer\u2026',
      hero_bridge_engine: 'Next \u2014 in the practice workspace, every line is checked.',
      hero_bridge_tutor: 'Then \u2014 connect live with a tutor on Google Meet.',
      hero_tutor_aria: 'Animated preview: weekly live tutoring on Google Meet',
      hero_tutor_meet_label: 'Google Meet',
      hero_tutor_live_badge: 'Live',
      hero_tutor_title: 'Weekly live session',
      hero_tutor_sub: 'Review progress, work through harder problems, and stay on track with a real teacher.',
      hero_tutor_tile_you: 'You',
      hero_tutor_tile_tutor: 'Tutor',
      hero_tutor_extra: 'Bring questions from this week\u2019s practice \u2192',
      problem_section_label: 'Why students struggle',
      problem_section_title: 'Sound familiar?',
      problem_1_h3: 'Nobody to ask for help',
      problem_1_p: "Your student gets stuck on homework and has no one to turn to. They wait until the next session \u2014 or worse, give up. Algebra doesn\u2019t pause for anyone.",
      problem_2_h3: 'AI tools just hand over the answer',
      problem_2_p: "Most apps show the solution without teaching the thinking. That\u2019s not learning \u2014 it\u2019s copying. Students miss the understanding behind each step.",
      problem_3_h3: "One weekly session isn\u2019t enough",
      problem_3_p: 'Private tutoring is valuable, but students need daily practice to build fluency. Without it, lessons don\u2019t stick between sessions.',
      how_section_label: 'How it works',
      how_section_title: 'Simple. Guided. Effective.',
      step_1_h3: 'Enroll online',
      step_1_p: 'Choose your plan and get immediate access to the full curriculum \u2014 no scheduling, no waiting.',
      step_2_h3: 'Practice with the Guided Practice Engine',
      step_2_p: 'The Guided Practice Engine walks through problems step by step, giving targeted hints when students are stuck \u2014 never just handing over the answer.',
      step_3_h3: 'Get tutored live',
      step_3_p: 'Weekly Google Meet sessions with a real teacher to review progress, answer harder questions, and keep momentum going.',
      curriculum_section_label: 'Curricula available',
      curriculum_section_title: 'Choose the best curriculum path',
      curriculum_section_sub: 'Nuvo Math supports multiple curriculum tracks so families can choose the framework that matches their school and goals.',
      curriculum_section_badge: 'Multi-curriculum support \u00B7 Grades 6\u20139 + UTP admission prep',
      curriculum_cambridge_name: 'Cambridge Lower Secondary',
      curriculum_cambridge_sub: 'A structured international pathway for grades 6\u20139 focused on deep conceptual understanding and progression.',
      curriculum_cambridge_body: 'Clear stage-by-stage progression with strong emphasis on algebraic fluency, reasoning, and exam readiness.',
      curriculum_cambridge_p1: 'Algebraic Foundations: variables, terms, expressions, and substitution',
      curriculum_cambridge_p2: 'Expanding & Simplifying: distributive property and collecting like terms',
      curriculum_cambridge_p3: 'Factorising: common factors and inverse expansion',
      curriculum_cambridge_p4: 'Linear Equations & Inequalities: one-step, two-step, and both-sides equations',
      curriculum_cambridge_p5: 'Formulae & Rearranging: substitution and changing the subject',
      curriculum_cambridge_p6: 'Sequences: term-to-term rules and nth-term expressions',
      curriculum_cambridge_p7: 'Simultaneous Equations: substitution and elimination',
      curriculum_cambridge_p8: 'Linear Functions & Graphs: coordinate pairs, gradient, and y = mx + c',
      curriculum_commoncore_name: 'Common Core (US)',
      curriculum_commoncore_sub: 'Skills-aligned progression for middle school students with emphasis on problem solving and real-world application.',
      curriculum_commoncore_body: 'Focuses on conceptual understanding, procedural skill, and application through context-rich tasks.',
      curriculum_commoncore_p1: 'Grade 6 Expressions: variables, equivalent expressions, and one-step equations',
      curriculum_commoncore_p2: 'Grade 6 Inequalities: notation, number lines, and simple constraints',
      curriculum_commoncore_p3: 'Grade 7 Equations: two-step equations, proportional reasoning, and percent contexts',
      curriculum_commoncore_p4: 'Grade 7 Expressions: expanding, factoring common factors, and mixed signs',
      curriculum_commoncore_p5: 'Grade 8 Functions: input-output rules, linear relationships, and graphs',
      curriculum_commoncore_p6: 'Grade 8 Systems & Modeling: equations in context and graph interpretation',
      curriculum_ib_name: 'IB MYP Mathematics',
      curriculum_ib_sub: 'Inquiry-driven curriculum that connects algebra to communication, reasoning, and authentic contexts.',
      curriculum_ib_body: 'Balances technique with conceptual exploration and clear mathematical communication in structured criteria.',
      curriculum_ib_p1: 'MYP Year 1: variables, expressions, substitution, and simple equations',
      curriculum_ib_p2: 'MYP Year 2: expanding, factorising, inequalities, and nth-term rules',
      curriculum_ib_p3: 'MYP Year 3: double brackets, simultaneous equations, and rearranging formulae',
      curriculum_ib_p4: 'MYP Year 3–4 Functions: linear graphs, quadratic patterns, domain, and range',
      curriculum_ib_p5: 'MYP Year 4 Extension: quadratics, systems, and advanced algebra modeling',
      curriculum_paa_name: 'UTP Admission Prep (PAA)',
      curriculum_paa_sub: 'Targeted preparation for the UTP admission exam.',
      curriculum_paa_body: 'Designed for fast exam transfer with included sections on:',
      curriculum_paa_p1: 'Aritm\u00E9tica: operations, ratios, percentages, patterns, and number theory',
      curriculum_paa_p2: '\u00C1lgebra: expressions, equations, functions, and systems',
      curriculum_paa_p3: 'Geometr\u00EDa: coordinates, shapes, area, and volume',
      curriculum_paa_p4: 'Data Analysis and Probability: statistics, graphs, counting, and probability',
      pricing_section_label: 'Plans',
      pricing_section_title: 'Simple pricing',
      pricing_section_sub: 'No contracts, no extras. Choose the plan that best fits their needs.',
      plan_practice_name: 'Basic Plan',
      plan_practice_f1: 'Full 7-unit curriculum',
      plan_practice_f2: 'Guided Practice Engine \u2014 step-by-step practice',
      plan_practice_f3: 'Unlimited problems',
      plan_practice_f4: 'Progress tracking dashboard',
      plan_practice_cta: 'Get full access',
      plan_popular: 'Most Popular',
      plan_tutoring_name: 'Pro Plan',
      plan_tutoring_f1: 'Everything in the Basic plan',
      plan_tutoring_f2: '4 live sessions/month via Google Meet',
      plan_tutoring_f3: 'Personalized homework assignments',
      plan_tutoring_f4: 'Direct WhatsApp support',
      plan_tutoring_cta: 'Get full access',
      pricing_note: 'No contracts. Cancel anytime.',

      // === PAA curriculum ===
      paa_curriculum_label: 'PAA',
      paa_unit_aritmetica:  'Aritm\u00E9tica',
      guest_paa_home_title: 'UTP Admission Test \u2014 Nuvo Math',
      guest_paa_home_header_title: 'UTP Admission Test',
      guest_paa_home_subtitle: 'Select a unit to begin',
      guest_paa_trial_banner: 'Guest mode \u2014 Arithmetic is free to try (5 guided problems per browser). Enroll for full access.',
      guest_secondary_home_title: 'Secondary Math \u2014 Nuvo Math',
      guest_secondary_home_header_title: 'Secondary School Math',
      guest_secondary_home_subtitle: 'Select a unit to begin',
      guest_secondary_badge: 'Secondary Math',
      guest_secondary_trial_banner: 'Guest mode \u2014 one algebra unit is free to try (5 guided problems per browser). Enroll for the full curriculum.',
      guest_secondary_card1_title: 'Algebra Foundations',
      guest_secondary_card1_desc: 'Expressions, like terms, and core algebra skills',
      guest_secondary_card2_title: 'Linear Equations',
      guest_secondary_card2_desc: 'One-step, two-step, and multi-step equations',
      guest_secondary_card3_title: 'Functions and Graphs',
      guest_secondary_card3_desc: 'Patterns, coordinate plane, and linear relationships',
      guest_secondary_card4_title: 'Advanced Algebra',
      guest_secondary_card4_desc: 'Factorisation, systems, and higher-level practice',
      guest_secondary_unit_desc_generic: 'Cambridge-aligned algebra content with 4 guided levels',
      guest_unit_arit_title: 'Arithmetic',
      guest_unit_arit_desc: 'Operations, ratios, percentages, and number theory',
      guest_unit_algebra_title: 'Algebra',
      guest_unit_algebra_desc: 'Expressions, equations, functions, and systems',
      guest_unit_geo_title: 'Geometry',
      guest_unit_geo_desc: 'Coordinates, figures, areas, and volumes',
      guest_unit_data_title: 'Data Analysis and Probability',
      guest_unit_data_desc: 'Statistics, charts, counting, and probability',
      guest_unit_available: 'Available',
      guest_unit_locked: '\uD83D\uDD12 Subscribe to unlock',
      guest_login_cta: 'Sign in',
      guest_lesson_complete_title: 'You completed Arithmetic Level 1!',
      guest_lesson_complete_subtitle: 'Subscribe to continue with the next levels and unlock Algebra, Geometry, and more.',
      guest_lesson_complete_title_secondary: 'You completed Algebra Level 1!',
      guest_lesson_complete_subtitle_secondary: 'Subscribe to continue to higher levels and unlock the full secondary curriculum.',

      // === filter.html ===
      filter_heading: 'What do you want to practice?',
      filter_sub: 'Choose the option that best fits what you need.',
      filter_card1_title: 'UTP Admission Test',
      filter_card1_desc: 'Prepare for the university admission exam with guided practice in Arithmetic, Algebra, Geometry, and more.',
      filter_card1_btn: 'Get started \u2192',
      filter_card2_title: 'Secondary School Math',
      filter_card2_desc: 'Strengthen algebra and math for grades 6\u20139 with the Cambridge, Common Core, or IB curriculum.',
      filter_card2_btn: 'Get started \u2192',
      filter_back: '\u2190 Back',

      // === trial.html (enrollment) ===
      trial_doc_title: 'Enrollment \u2014 Nuvo Math',
      trial_meta_description: 'Request student access to Nuvo Math. Choose a plan; we follow up with payment and login details.',
      trial_form_eyebrow: 'Enrollment',
      trial_form_heading: 'Request your student account',
      trial_form_sub: 'Share your details and choose a plan. We follow up within a few hours to confirm payment (Yappy, bank transfer, etc.) and send login access.',
      trial_label_parent_name: 'Parent name',
      trial_label_parent_email: 'Parent email',
      trial_label_student_name: 'Student name',
      trial_label_student_grade: 'Student grade',
      trial_label_plan: 'Plan',
      trial_label_whatsapp_optional: 'WhatsApp number (optional)',
      trial_grade_ph: 'Select a grade',
      trial_plan_ph: 'Select a plan',
      trial_grade_6: 'Grade 6',
      trial_grade_7: 'Grade 7',
      trial_grade_8: 'Grade 8',
      trial_grade_9: 'Grade 9',
      trial_plan_opt_practice: 'Basic Plan \u2014 $29/month',
      trial_plan_opt_tutoring: 'Pro Plan \u2014 $99/month',
      trial_whatsapp_ph: 'Optional \u2014 for faster support',
      trial_submit_btn: 'Send my details',
      trial_form_note: 'We reply within a few hours with payment options and next steps before activating your account.',
      trial_thankyou_heading: 'You\u2019re all set!',
      trial_thankyou_body: 'Check your email \u2014 we will send follow-up and your student login within a few hours. Questions? WhatsApp 6014-1676.',
      trial_banner_guest_cap: 'You used your 5 free guest practice problems. Complete the form below to enroll and keep practicing.',
      trial_banner_guest_lesson: 'Great work on the free preview. Enroll below to unlock the full curriculum.',
      trial_banner_access_ended: 'Your preview access period ended. Use this form to renew or subscribe.',
      trial_banner_active_prefix: 'Preview access \u00b7',
      trial_banner_active_mid: 'left \u2014',
      trial_banner_active_link: 'Enroll to keep practicing',
      trial_day_singular: 'day',
      trial_day_plural: 'days',

      // === guest paywall ===
      guest_paywall_title: 'Ready to keep practicing?',
      guest_paywall_subtitle: 'You\u2019ve completed your free practice. Subscribe to access all levels of the Admission Test \u2014 Arithmetic, Algebra, Geometry, and more.',
      guest_paywall_subtitle_secondary: 'You\u2019ve completed your free practice. Subscribe to unlock all secondary units and levels.',
      guest_paywall_subscribe_btn: 'Request full access \u2192',
      guest_paywall_login_btn: 'I have an account \u2192 Sign in',
      guest_paywall_contact: 'Questions? WhatsApp 6014-1676'
    },

    es: {
      // === SHARED NAV / FOOTER ===
      nav_how_it_works: 'C\u00F3mo funciona',
      nav_curriculum: 'Plan de estudios',
      nav_pricing: 'Precios',
      nav_signout: 'Cerrar sesi\u00F3n',
      nav_signin: 'Iniciar sesi\u00F3n',
      nav_get_started: 'Empezar',
      footer_copy: '\u00A9 2026 Nuvo Math \u00B7 nuvostudio.club',
      footer_tagline: 'Pr\u00E1ctica de Matem\u00E1ticas que realmente ense\u00F1a. Pr\u00E1ctica guiada paso a paso y tutor\u00EDas en vivo.',
      loading_just_moment: '\u00A1Un momento!',

      // === login.html ===
      login_label: 'Acceso de Estudiante',
      login_heading: 'Bienvenido de nuevo',
      login_sub: 'Ingresa tu ID de estudiante para continuar',
      login_id_label: 'ID de estudiante',
      login_id_placeholder: 'ej. sofia',
      login_submit: 'Entrar \u2192',
      login_error_notfound: 'ID no encontrado \u2014 consulta a tu maestro',
      login_no_account: '\u00BFNo tienes cuenta?',
      login_trial_link: 'Solicitar inscripci\u00F3n \u2192',
      login_signing_in: 'Entrando\u2026',
      login_error_generic: 'Algo sali\u00F3 mal. Int\u00E9ntalo de nuevo.',
      login_error_network: 'Error de red. Verifica tu conexi\u00F3n e int\u00E9ntalo de nuevo.',

      // === home.html ===
      welcome_back: 'Hola de nuevo,',
      curriculum_loading: 'Cargando tu plan de estudios\u2026',
      section_your_curriculum: 'Tu plan de estudios',
      unit_label: 'Unidad',
      level_label: 'Nivel',
      home_help_link: '\u00BFNecesitas ayuda? Preg\u00FAntale a Ronel',
      home_session_note: 'Tu pr\u00F3xima sesi\u00F3n: revisa WhatsApp para coordinar',
      home_offline: 'Sin conexi\u00F3n \u2014 verifica tu red',
      trial_expired_heading: 'Tu acceso ha finalizado',
      trial_expired_body: 'Env\u00EDa el formulario de inscripci\u00F3n para elegir plan y coordinar el pago. Normalmente respondemos en pocas horas.',
      trial_expired_note: '\u00BFPreguntas? tutor@nuvostudio.club o WhatsApp 6014-1676.',
      trial_practice_btn: 'Formulario de inscripci\u00F3n \u2192',
      trial_tutoring_btn: 'Escr\u00EDbenos por WhatsApp \u2192',

      // === lesson.html ===
      back_to_curriculum: '\u2190 Volver al plan de estudios',
      loading_lesson_h2: 'Cargando lecci\u00F3n\u2026',
      error_missing_params_h2: 'Par\u00E1metros de lecci\u00F3n faltantes',
      error_missing_params_p: 'Esta p\u00E1gina requiere los par\u00E1metros <code>curriculum</code>, <code>unit</code> y <code>stage</code> en la URL.',
      error_lesson_not_found_h2: 'Lecci\u00F3n no encontrada',
      error_load_failed_h2: 'No se pudo cargar la lecci\u00F3n',
      error_load_failed_p: 'Verifica tu conexi\u00F3n a internet y actualiza la p\u00E1gina.',
      phase_intro: 'Intro',
      phase_concepts: 'Conceptos',
      phase_example: 'Ejemplo',
      phase_practice: 'Pr\u00E1ctica',
      phase_test: 'Prueba',
      cover_begin_btn: 'Comenzar lecci\u00F3n \u2192',
      concepts_card_title: 'Conceptos clave',
      concepts_no_rules: 'No hay reglas listadas.',
      concepts_next_btn: 'Entendido \u2014 mu\u00E9strame un ejemplo \u2192',
      concept_tab_written: 'Redacci\u00F3n',
      concept_tab_visual: 'Visual',
      concept_tab_formula: 'F\u00F3rmula',
      concept_tab_voice: 'Voz',
      concept_visual_step: 'Idea',
      formula_no_items: 'A\u00FAn no hay f\u00F3rmulas listadas.',
      voice_listen_btn: 'Escuchar',
      voice_stop_btn: 'Detener',
      voice_no_text: 'A\u00FAn no hay narraci\u00F3n disponible.',
      example_card_title: 'Ejemplo resuelto',
      example_tab_symbolic: 'Simb\u00F3lico',
      example_tab_visual: 'Visual',
      example_visual_empty: 'La representaci\u00F3n visual aparecer\u00E1 aqu\u00ED.',
      example_narration_init: 'Sigue el ejemplo \u2014 toca el bot\u00F3n de abajo para avanzar paso a paso.',
      example_btn_previous: '\u2190 Anterior',
      example_btn_show_step_n: 'Mostrar paso {n}',
      example_btn_goto_practice: 'Ir a la pr\u00E1ctica \u2192',
      example_btn_try_yourself: 'Int\u00E9ntalo t\u00FA mismo \u2192',
      practice_tag: 'Pr\u00E1ctica',
      practice_subtitle: 'Resuelve estos problemas de pr\u00E1ctica. Hay pistas disponibles.',
      test_tag: 'Prueba de nivel',
      test_subtitle: '\u00A1Responde todas las preguntas. Sin pistas esta vez!',
      result_complete: '\u00A1Completado!',
      result_level_complete: '\u00A1Nivel completado!',
      result_great_work: '\u00A1Buen trabajo! El siguiente nivel est\u00E1 desbloqueado.',
      result_score_correct: 'Obtuviste {score} de {total} correctas.',
      result_back_btn: 'Volver al plan de estudios \u2192',
      result_fail_h2: '\u00A1Sigue practicando!',
      result_fail_review: 'Revisa el ejemplo de nuevo e intenta la prueba una vez m\u00E1s.',
      result_fail_btn: 'Revisar el ejemplo \u2192',

      // === dashboard.html ===
      loading_problems_h2: 'Cargando tus problemas\u2026',
      error_no_student_h2: 'ID de estudiante no encontrado',
      error_no_student_p: 'As\u00E9g\u00FArate de haber abierto el enlace correcto. \u00A1Consulta a tu maestro si no est\u00E1s seguro!',
      error_student_notfound_h2: 'Estudiante no encontrado',
      error_student_notfound_p: 'No encontramos un estudiante con el ID {id}. Verifica tu enlace o consulta a tu maestro.',
      error_load_problems_h2: 'No se pudieron cargar tus problemas',
      error_load_problems_p: 'Verifica tu conexi\u00F3n a internet y actualiza la p\u00E1gina.',
      dashboard_hi: '¡Hola,',
      dashboard_problems_label: 'Problemas completados',
      dashboard_no_problems: 'A\u00FAn no hay problemas asignados.',
      dashboard_all_done: '\u00A1Incre\u00EDble \u2014 terminaste todo! \uD83C\uDF89',
      dashboard_get_started: '\u00A1Toca un problema para comenzar!',
      dashboard_keep_going: '\u00A1Sigue adelante \u2014 te quedan {n}!',
      dashboard_completed: 'Completado',
      dashboard_not_started: 'Sin comenzar',
      dashboard_practice_again: 'Practicar de nuevo \u2192',
      dashboard_your_problems: 'Tus problemas',
      dashboard_all_done_banner: '\u00A1Terminaste todos tus problemas \u2014 excelente trabajo!',
      dashboard_generating: 'Generando\u2026',
      dashboard_try_again: 'Intentar de nuevo',

      // === teacher.html ===
      teacher_login_h2: 'Acceso de Maestro',
      teacher_login_p: 'Ingresa tu contrase\u00F1a de maestro para continuar.',
      teacher_password_placeholder: 'Contrase\u00F1a',
      teacher_unlock_btn: 'Desbloquear',
      teacher_dashboard_h1: 'Panel del Maestro',
      teacher_subtitle: 'Nuvo Studio',
      teacher_tab_students: 'Estudiantes y Tareas',
      teacher_tab_problems: 'Banco de Problemas',
      teacher_all_students: 'TODOS LOS ESTUDIANTES',
      teacher_loading: 'Cargando\u2026',
      teacher_new_student_btn: '+ Nuevo Estudiante',
      teacher_select_student: 'Selecciona un estudiante de la lista para comenzar.',
      teacher_student_profile: 'Perfil del Estudiante',
      teacher_edit_btn: 'Editar \u270F\uFE0F',
      teacher_edit_profile: 'Editar Perfil',
      teacher_label_name: 'Nombre',
      teacher_label_student_id: 'ID de Estudiante',
      teacher_label_curriculum: 'Plan de Estudios',
      teacher_label_grade: 'Grado / Etapa',
      teacher_label_trial: 'Vencimiento de prueba',
      teacher_optional: '(opcional)',
      teacher_auto_generated: '(generado autom\u00E1ticamente)',
      teacher_calc_hint: '(toca Pregunta o Respuesta primero)',
      teacher_save_btn: 'Guardar',
      teacher_cancel_btn: 'Cancelar',
      teacher_new_student_title: 'Nuevo Estudiante',
      teacher_create_btn: 'Crear Estudiante',
      teacher_homework_title: 'Tarea',
      teacher_homework_note: 'Los problemas asignados aparecen en la pantalla de inicio del estudiante bajo \u201CTu tarea\u201D',
      teacher_no_homework: 'A\u00FAn no hay tarea asignada',
      teacher_assign_label: 'Asignar desde el banco de problemas',
      teacher_problem_id_placeholder: 'ID del Problema',
      teacher_assign_btn: 'Asignar',
      teacher_oneoff_heading: 'O crea un problema \u00FAnico',
      teacher_question_label: 'Pregunta',
      teacher_word_desc: 'Descripci\u00F3n en palabras',
      teacher_answer_label: 'Respuesta',
      teacher_expected_answer: 'Respuesta esperada',
      teacher_add_assign_btn: 'Agregar y asignar',
      teacher_student_link_label: 'Enlace del estudiante:',
      teacher_copy_link_btn: 'Copiar enlace',
      teacher_problems_title: 'Problemas',
      teacher_add_to_bank_title: 'Agregar al Banco',
      teacher_unit_label: 'Unidad',
      teacher_level_label: 'Nivel',
      teacher_problem_type_label: 'Tipo de Problema',
      teacher_math_type_label: 'Tipo de Matem\u00E1ticas',
      teacher_calc_label: 'Calculadora',
      teacher_hint_label_1: 'Pista 1',
      teacher_hint_label_2: 'Pista 2',
      teacher_hint_label_3: 'Pista 3',
      teacher_add_hints: 'Agregar pistas \u25BE',
      teacher_hide_hints: 'Agregar pistas \u25B4',
      teacher_pid_label: 'ID del Problema',
      teacher_save_to_bank_btn: 'Guardar en el banco',
      teacher_saved_to_bank: 'Guardado en el banco \u2713',
      teacher_no_problems: 'Sin problemas a\u00FAn.',
      teacher_pf_curriculum_grade: 'Plan de Estudios y Grado',
      teacher_trial_expired_label: 'Vencido',
      teacher_trial_days_left: '{n}d restantes',
      teacher_auth_error_empty: 'Por favor ingresa una contrase\u00F1a.',
      teacher_id_required: 'El ID y el nombre son requeridos.',
      teacher_saving: 'Guardando\u2026',
      teacher_creating: 'Creando\u2026',
      teacher_steps_show: 'Pasos \u25BE',
      teacher_steps_hide: 'Pasos \u25B4',
      teacher_no_attempts: 'Sin intentos a\u00FAn.',
      teacher_loading_logs: 'Cargando\u2026',
      teacher_failed_logs: 'Error al cargar los registros.',
      teacher_toast_select_student: 'Selecciona un estudiante primero.',
      teacher_toast_enter_pid: 'Ingresa un ID de problema.',
      teacher_toast_problem_notfound: 'Problema \u201C{pid}\u201D no encontrado en el banco.',
      teacher_toast_already_assigned: 'Ya asignado.',
      teacher_toast_assigned: 'Problema asignado.',
      teacher_toast_enter_qna: 'Ingresa la pregunta y la respuesta.',
      teacher_toast_oneoff_assigned: 'Problema \u00FAnico asignado.',
      teacher_toast_link_copied: '\u00A1Enlace copiado!',
      teacher_toast_fill_required: 'Por favor completa todos los campos requeridos.',
      teacher_toast_wrong_password: 'Contrase\u00F1a incorrecta.',
      teacher_toast_failed_save: 'Error al guardar. Verifica tu conexi\u00F3n.',
      teacher_toast_failed_create: 'Error al crear. Verifica tu conexi\u00F3n.',
      teacher_toast_failed_homework: 'Error al guardar la tarea. Verifica tu conexi\u00F3n.',
      teacher_toast_failed_student: 'Error al cargar los datos del estudiante.',
      teacher_toast_failed_students: 'No se pudo cargar la lista de estudiantes.',
      teacher_toast_failed_problems: 'No se pudo cargar los problemas.',
      hw_tag_diagnostic: 'Diagn\u00F3stico',
      hw_tag_test: 'Prueba',
      hw_tag_oneoff: '\u00DAnico',
      hw_tag_practice: 'Pr\u00E1ctica',
      filter_all: 'Todos',

      // === index.html ===
      hero_eyebrow: 'Matem\u00E1ticas guiadas + tutor\u00EDas en vivo',
      hero_headline: 'Prep\u00E1rate para el examen de la UTP.',
      hero_sub: '<strong>Practica cuando quieras.</strong> Pr\u00E1ctica guiada paso a paso con pistas, ejemplos y retroalimentaci\u00F3n inmediata \u2014 para que llegues al examen con confianza.',
      hero_cta_primary: 'Empezar a practicar',
      hero_cta_secondary: 'Ver c\u00F3mo funciona',
      hero_signin_note: '\u00BFYa inscrito?',
      hero_signin_link: 'Iniciar sesi\u00F3n \u2192',
      hero_demo_aria: 'Vista previa animada: pr\u00E1ctica guiada con pista y retroalimentaci\u00F3n al instante',
      hero_demo_title: 'Pr\u00E1ctica guiada',
      hero_demo_prompt: 'Resuelve para x: 2x + 3 = 11',
      hero_demo_step_label: 'Paso 1 de 3',
      hero_demo_step_q: '\u00BFQu\u00E9 haces primero para aislar el t\u00E9rmino con x?',
      hero_demo_hint_tag: 'Pista',
      hero_demo_hint_text: 'Resta 3 en ambos lados.',
      hero_demo_feedback: 'Bien \u2014 as\u00ED la ecuaci\u00F3n se mantiene balanceada.',
      hero_engine_aria: 'Vista previa: cada l\u00EDnea que escribes se eval\u00FAa antes de seguir',
      hero_engine_count: '1/1',
      hero_engine_meta: 'Problema 1 de 1 \u00B7 Simplificar',
      hero_engine_expr: '3x \u2212 2y + 6x + 9y',
      hero_engine_line1: '(3x + 6x) + (\u22122y + 9y)',
      hero_engine_line2: '9x + (\u22122y + 9y)',
      hero_engine_nudge: '\u00A1Valor correcto, pero intenta simplificar o factorizar m\u00E1s!',
      hero_engine_placeholder: 'Escribe o usa los botones para ingresar tu respuesta\u2026',
      hero_bridge_engine: 'Siguiente \u2014 en el espacio de pr\u00E1ctica, cada l\u00EDnea se revisa.',
      hero_bridge_tutor: 'Despu\u00E9s \u2014 conecta en vivo con tu tutor por Google Meet.',
      hero_tutor_aria: 'Vista previa: tutor\u00EDa en vivo semanal por Google Meet',
      hero_tutor_meet_label: 'Google Meet',
      hero_tutor_live_badge: 'En vivo',
      hero_tutor_title: 'Sesi\u00F3n en vivo semanal',
      hero_tutor_sub: 'Revisa tu avance, resuelve lo m\u00E1s dif\u00edcil y mant\u00E9n el ritmo con un maestro de verdad.',
      hero_tutor_tile_you: 'T\u00FA',
      hero_tutor_tile_tutor: 'Tutor',
      hero_tutor_extra: 'Trae dudas de la pr\u00E1ctica de esta semana \u2192',
      problem_section_label: 'Por qu\u00E9 los estudiantes tienen dificultades',
      problem_section_title: '\u00BFTe suena familiar?',
      problem_1_h3: 'Nadie a quien pedir ayuda',
      problem_1_p: 'Tu estudiante se queda atascado en la tarea y no tiene a quien recurrir. Espera hasta la pr\u00F3xima sesi\u00F3n \u2014 o peor, se rinde. El \u00E1lgebra no espera por nadie.',
      problem_2_h3: 'Las herramientas de IA simplemente dan la respuesta',
      problem_2_p: 'La mayor\u00EDa de las apps muestran la soluci\u00F3n sin ense\u00F1ar el razonamiento. Eso no es aprender \u2014 es copiar. Los estudiantes pierden la comprensi\u00F3n detr\u00E1s de cada paso.',
      problem_3_h3: 'Una sesi\u00F3n semanal no es suficiente',
      problem_3_p: 'La tutor\u00EDa privada es valiosa, pero los estudiantes necesitan pr\u00E1ctica diaria para desarrollar fluidez. Sin ella, las clases no se retienen entre sesiones.',
      how_section_label: 'C\u00F3mo funciona',
      how_section_title: 'Simple. Guiado. Efectivo.',
      step_1_h3: 'Inscr\u00EDbete en l\u00EDnea',
      step_1_p: 'Elige tu plan y obt\u00E9n acceso inmediato al plan de estudios completo \u2014 sin programar, sin esperar.',
      step_2_h3: 'Practica con el Motor de Pr\u00E1ctica Guiada',
      step_2_p: 'El Motor de Pr\u00E1ctica Guiada recorre los problemas paso a paso, dando pistas precisas cuando los estudiantes se quedan atascados \u2014 sin simplemente dar la respuesta.',
      step_3_h3: 'Recibe tutor\u00EDa en vivo',
      step_3_p: 'Sesiones semanales por Google Meet con un maestro real para revisar el progreso, responder preguntas m\u00E1s dif\u00EDciles y mantener el impulso.',
      curriculum_section_label: 'Curr\u00EDculos disponibles',
      curriculum_section_title: 'Elige la ruta curricular ideal',
      curriculum_section_sub: 'Para que cada estudiante elija el marco que mejor se alinea con su colegio u objetivos.',
      curriculum_section_badge: 'Soporte multi-curr\u00EDculo \u00B7 Grados 6\u20139 + preparaci\u00F3n de admisi\u00F3n UTP',
      curriculum_cambridge_name: 'Cambridge Lower Secondary',
      curriculum_cambridge_sub: 'Ruta internacional estructurada para grados 6\u20139, enfocada en comprensi\u00F3n profunda y progresi\u00F3n por etapas.',
      curriculum_cambridge_body: 'Progresi\u00F3n clara por niveles con fuerte \u00E9nfasis en fluidez algebraica, razonamiento y preparaci\u00F3n para evaluaciones.',
      curriculum_cambridge_p1: 'Fundamentos de \u00C1lgebra: variables, t\u00E9rminos, expresiones y sustituci\u00F3n',
      curriculum_cambridge_p2: 'Expansi\u00F3n y Simplificaci\u00F3n: propiedad distributiva y t\u00E9rminos semejantes',
      curriculum_cambridge_p3: 'Factorizaci\u00F3n: factores comunes e inversa de la expansi\u00F3n',
      curriculum_cambridge_p4: 'Ecuaciones e Inecuaciones Lineales: ecuaciones de uno, dos y ambos lados',
      curriculum_cambridge_p5: 'F\u00F3rmulas y Despejes: sustituci\u00F3n y cambio de sujeto',
      curriculum_cambridge_p6: 'Sucesiones: reglas t\u00E9rmino a t\u00E9rmino y expresiones del t\u00E9rmino n',
      curriculum_cambridge_p7: 'Ecuaciones Simult\u00E1neas: sustituci\u00F3n y eliminaci\u00F3n',
      curriculum_cambridge_p8: 'Funciones Lineales y Gr\u00E1ficas: pares ordenados, pendiente y y = mx + c',
      curriculum_commoncore_name: 'Common Core (EE. UU.)',
      curriculum_commoncore_sub: 'Progresi\u00F3n alineada por habilidades para secundaria, con \u00E9nfasis en resoluci\u00F3n de problemas y aplicaci\u00F3n real.',
      curriculum_commoncore_body: 'Prioriza comprensi\u00F3n conceptual, dominio procedimental y aplicaci\u00F3n mediante tareas contextualizadas.',
      curriculum_commoncore_p1: 'Grado 6 Expresiones: variables, expresiones equivalentes y ecuaciones de un paso',
      curriculum_commoncore_p2: 'Grado 6 Inecuaciones: notaci\u00F3n, recta num\u00E9rica y restricciones simples',
      curriculum_commoncore_p3: 'Grado 7 Ecuaciones: ecuaciones de dos pasos, proporcionalidad y porcentajes',
      curriculum_commoncore_p4: 'Grado 7 Expresiones: expansi\u00F3n, factor com\u00FAn y signos mixtos',
      curriculum_commoncore_p5: 'Grado 8 Funciones: reglas entrada-salida, relaciones lineales y gr\u00E1ficas',
      curriculum_commoncore_p6: 'Grado 8 Sistemas y Modelaci\u00F3n: ecuaciones en contexto e interpretaci\u00F3n gr\u00E1fica',
      curriculum_ib_name: 'Matem\u00E1tica IB MYP',
      curriculum_ib_sub: 'Curr\u00EDculo basado en indagaci\u00F3n que conecta el \u00E1lgebra con comunicaci\u00F3n, razonamiento y contextos aut\u00E9nticos.',
      curriculum_ib_body: 'Equilibra t\u00E9cnica con exploraci\u00F3n conceptual y comunicaci\u00F3n matem\u00E1tica clara dentro de criterios estructurados.',
      curriculum_ib_p1: 'MYP A\u00F1o 1: variables, expresiones, sustituci\u00F3n y ecuaciones simples',
      curriculum_ib_p2: 'MYP A\u00F1o 2: expansi\u00F3n, factorizaci\u00F3n, inecuaciones y reglas del t\u00E9rmino n',
      curriculum_ib_p3: 'MYP A\u00F1o 3: doble par\u00E9ntesis, ecuaciones simult\u00E1neas y despejes',
      curriculum_ib_p4: 'MYP A\u00F1os 3\u20134 Funciones: gr\u00E1ficas lineales, patrones cuadr\u00E1ticos, dominio y rango',
      curriculum_ib_p5: 'MYP A\u00F1o 4 Extensi\u00F3n: cuadr\u00E1ticas, sistemas y modelaci\u00F3n algebraica avanzada',
      curriculum_paa_name: 'Preparaci\u00F3n de Admisi\u00F3n UTP (PAA)',
      curriculum_paa_sub: 'Preparaci\u00F3n focalizada para la prueba de admisi\u00F3n de la UTP.',
      curriculum_paa_body: 'Dise\u00F1ado para transferencia r\u00E1pida al examen con secciones incluidas de:',
      curriculum_paa_p1: 'Aritm\u00E9tica: operaciones, razones, porcentajes, patrones y teor\u00EDa de n\u00FAmeros',
      curriculum_paa_p2: '\u00C1lgebra: expresiones, ecuaciones, funciones y sistemas',
      curriculum_paa_p3: 'Geometr\u00EDa: coordenadas, figuras, \u00E1rea y volumen',
      curriculum_paa_p4: 'An\u00E1lisis de Datos y Probabilidad: estad\u00EDstica, gr\u00E1ficas, conteo y probabilidad',
      pricing_section_label: 'Planes',
      pricing_section_title: 'Precios simples',
      pricing_section_sub: 'Sin contratos, sin extras. Elige el plan que mejor se adapte a sus necesidades.',
      plan_practice_name: 'Plan B\u00E1sico',
      plan_practice_f1: 'Plan de estudios completo de 7 unidades',
      plan_practice_f2: 'Motor de Pr\u00E1ctica Guiada \u2014 pr\u00E1ctica paso a paso',
      plan_practice_f3: 'Problemas ilimitados',
      plan_practice_f4: 'Panel de seguimiento de progreso',
      plan_practice_cta: 'Obtener acceso completo',
      plan_popular: 'M\u00E1s Popular',
      plan_tutoring_name: 'Plan Pro',
      plan_tutoring_f1: 'Todo lo del Plan B\u00E1sico',
      plan_tutoring_f2: '4 sesiones en vivo/mes por Google Meet',
      plan_tutoring_f3: 'Tareas personalizadas',
      plan_tutoring_f4: 'Soporte directo por WhatsApp',
      plan_tutoring_cta: 'Obtener acceso completo',
      pricing_note: 'Sin contratos. Cancela cuando quieras.',

      // === PAA curriculum ===
      paa_curriculum_label: 'PAA',
      paa_unit_aritmetica:  'Aritm\u00E9tica',
      guest_paa_home_title: 'Prueba de Admisi\u00F3n \u2014 UTP',
      guest_paa_home_header_title: 'Prueba de Admisi\u00F3n \u2014 UTP',
      guest_paa_home_subtitle: 'Selecciona una unidad para comenzar',
      guest_paa_trial_banner: 'Modo invitado: Aritm\u00E9tica gratis para probar (5 problemas guiados por navegador). Inscr\u00EDbete para acceso completo.',
      guest_secondary_home_title: 'Matem\u00E1ticas de Secundaria \u2014 Nuvo Math',
      guest_secondary_home_header_title: 'Matem\u00E1ticas de Secundaria',
      guest_secondary_home_subtitle: 'Selecciona una unidad para comenzar',
      guest_secondary_badge: 'Matem\u00E1ticas de Secundaria',
      guest_secondary_trial_banner: 'Modo invitado: una unidad de \u00E1lgebra gratis para probar (5 problemas guiados por navegador). Inscr\u00EDbete para el curr\u00EDculo completo.',
      guest_secondary_card1_title: 'Fundamentos de \u00C1lgebra',
      guest_secondary_card1_desc: 'Expresiones, t\u00E9rminos semejantes y habilidades base de \u00E1lgebra',
      guest_secondary_card2_title: 'Ecuaciones Lineales',
      guest_secondary_card2_desc: 'Ecuaciones de uno, dos y varios pasos',
      guest_secondary_card3_title: 'Funciones y Gr\u00E1ficas',
      guest_secondary_card3_desc: 'Patrones, plano cartesiano y relaciones lineales',
      guest_secondary_card4_title: '\u00C1lgebra Avanzada',
      guest_secondary_card4_desc: 'Factorizaci\u00F3n, sistemas y pr\u00E1ctica de mayor nivel',
      guest_secondary_unit_desc_generic: 'Contenido de \u00E1lgebra alineado a Cambridge con 4 niveles guiados',
      guest_unit_arit_title: 'Aritm\u00E9tica',
      guest_unit_arit_desc: 'Operaciones, razones, porcentajes y teor\u00EDa de n\u00FAmeros',
      guest_unit_algebra_title: '\u00C1lgebra',
      guest_unit_algebra_desc: 'Expresiones, ecuaciones, funciones y sistemas',
      guest_unit_geo_title: 'Geometr\u00EDa',
      guest_unit_geo_desc: 'Coordenadas, figuras, \u00E1reas y vol\u00FAmenes',
      guest_unit_data_title: 'An\u00E1lisis de datos y Probabilidad',
      guest_unit_data_desc: 'Estad\u00EDstica, gr\u00E1ficas, conteo y probabilidad',
      guest_unit_available: 'Disponible',
      guest_unit_locked: '\uD83D\uDD12 Suscr\u00EDbete para acceder',
      guest_login_cta: 'Iniciar sesi\u00F3n',
      guest_lesson_complete_title: '\u00A1Completaste Aritm\u00E9tica Nivel 1!',
      guest_lesson_complete_subtitle: 'Suscr\u00EDbete para continuar con los niveles siguientes y acceder a \u00C1lgebra, Geometr\u00EDa y m\u00E1s.',
      guest_lesson_complete_title_secondary: '\u00A1Completaste \u00C1lgebra Nivel 1!',
      guest_lesson_complete_subtitle_secondary: 'Suscr\u00EDbete para continuar a niveles superiores y desbloquear todo el curr\u00EDculo de secundaria.',

      // === filter.html ===
      filter_heading: '\u00BFQu\u00E9 quieres practicar?',
      filter_sub: 'Elige la opci\u00F3n que mejor se adapte a lo que necesitas.',
      filter_card1_title: 'Prueba de Admisi\u00F3n \u2014 UTP',
      filter_card1_desc: 'Prep\u00E1rate para el examen de admisi\u00F3n con pr\u00E1ctica guiada en Aritm\u00E9tica, \u00C1lgebra, Geometr\u00EDa y m\u00E1s.',
      filter_card1_btn: 'Empezar \u2192',
      filter_card2_title: 'Matem\u00E1ticas de Secundaria',
      filter_card2_desc: 'Refuerza \u00E1lgebra y matem\u00E1ticas de grados 6 a 9 con el curr\u00EDculo Cambridge, Common Core o IB.',
      filter_card2_btn: 'Empezar \u2192',
      filter_back: '\u2190 Volver',

      // === trial.html (inscripci\u00F3n) ===
      trial_doc_title: 'Inscripci\u00F3n \u2014 Nuvo Math',
      trial_meta_description: 'Solicita acceso para tu estudiante en Nuvo Math. Elige un plan; coordinamos pago y enviamos el acceso.',
      trial_form_eyebrow: 'Inscripci\u00F3n',
      trial_form_heading: 'Solicita la cuenta de tu estudiante',
      trial_form_sub: 'Completa los datos y elige un plan. Te contactamos en pocas horas para confirmar el pago (Yappy, transferencia, etc.) y enviar el acceso.',
      trial_label_parent_name: 'Nombre del padre/madre o tutor',
      trial_label_parent_email: 'Correo del padre/madre o tutor',
      trial_label_student_name: 'Nombre del estudiante',
      trial_label_student_grade: 'Grado del estudiante',
      trial_label_plan: 'Plan',
      trial_label_whatsapp_optional: 'WhatsApp (opcional)',
      trial_grade_ph: 'Selecciona un grado',
      trial_plan_ph: 'Selecciona un plan',
      trial_grade_6: 'Grado 6',
      trial_grade_7: 'Grado 7',
      trial_grade_8: 'Grado 8',
      trial_grade_9: 'Grado 9',
      trial_plan_opt_practice: 'Plan B\u00E1sico \u2014 $29/mes',
      trial_plan_opt_tutoring: 'Plan Pro \u2014 $99/mes',
      trial_whatsapp_ph: 'Opcional \u2014 para contactarte m\u00E1s r\u00E1pido',
      trial_submit_btn: 'Enviar mis datos',
      trial_form_note: 'Respondemos en pocas horas con opciones de pago y los siguientes pasos antes de activar la cuenta.',
      trial_thankyou_heading: '\u00A1Listo!',
      trial_thankyou_body: 'Revisa tu correo: te escribimos con el seguimiento y el acceso del estudiante en pocas horas. \u00BFDudas? WhatsApp 6014-1676.',
      trial_banner_guest_cap: 'Ya usaste los 5 problemas de pr\u00E1ctica gratuita. Completa el formulario para inscribirte y seguir practicando.',
      trial_banner_guest_lesson: '\u00A1Excelente trabajo en la vista previa! Inscr\u00EDbete abajo para desbloquear el curr\u00EDculo completo.',
      trial_banner_access_ended: 'Tu periodo de acceso de vista previa termin\u00F3. Usa este formulario para renovar o suscribirte.',
      trial_banner_active_prefix: 'Acceso de vista previa \u00b7 Quedan ',
      trial_banner_active_mid: ' \u2014 ',
      trial_banner_active_link: 'Inscr\u00EDbete para seguir',
      trial_day_singular: 'd\u00EDa',
      trial_day_plural: 'd\u00EDas',

      // === guest paywall ===
      guest_paywall_title: '\u00BFListo para seguir practicando?',
      guest_paywall_subtitle: 'Completaste tu pr\u00E1ctica gratuita. Suscr\u00EDbete para acceder a todos los niveles de la Prueba de Admisi\u00F3n \u2014 Aritm\u00E9tica, \u00C1lgebra, Geometr\u00EDa y m\u00E1s.',
      guest_paywall_subtitle_secondary: 'Completaste tu pr\u00E1ctica gratuita. Suscr\u00EDbete para desbloquear todas las unidades y niveles de secundaria.',
      guest_paywall_subscribe_btn: 'Solicitar acceso completo \u2192',
      guest_paywall_login_btn: 'Ya tengo cuenta \u2192 Iniciar sesi\u00F3n',
      guest_paywall_contact: '\u00BFPreguntas? WhatsApp 6014-1676'
    }
  };

  function getInitialLang() {
    try {
      var params = new URLSearchParams(window.location.search);
      var requested = params.get('lang');
      if (requested === 'en' || requested === 'es') {
        localStorage.setItem('nuvo_lang', requested);
        return requested;
      }

      var saved = localStorage.getItem('nuvo_lang');
      if (saved === 'en' || saved === 'es') return saved;
    } catch (e) {
      // If storage or URL parsing is unavailable, keep the product default.
    }

    return 'es';
  }

  var _lang = getInitialLang();

  window.Lang = {
    detect: function () { return _lang; },

    t: function (key) {
      return (STRINGS[_lang] || {})[key] || STRINGS.en[key] || key;
    },

    apply: function () {
      document.documentElement.lang = _lang;
      // textContent translations
      document.querySelectorAll('[data-i18n]').forEach(function (el) {
        el.textContent = window.Lang.t(el.getAttribute('data-i18n'));
      });
      // innerHTML translations (for strings containing HTML like <br>, <code>)
      document.querySelectorAll('[data-i18n-html]').forEach(function (el) {
        el.innerHTML = window.Lang.t(el.getAttribute('data-i18n-html'));
      });
      // placeholder translations
      document.querySelectorAll('[data-i18n-placeholder]').forEach(function (el) {
        el.placeholder = window.Lang.t(el.getAttribute('data-i18n-placeholder'));
      });
      // aria-label translations
      document.querySelectorAll('[data-i18n-aria-label]').forEach(function (el) {
        el.setAttribute('aria-label', window.Lang.t(el.getAttribute('data-i18n-aria-label')));
      });
    }
  };
}());
