(function () {
  'use strict';

  var STRINGS = {
    en: {
      // === SHARED NAV / FOOTER ===
      nav_how_it_works: 'How it works',
      nav_curriculum: 'Curriculum',
      nav_pricing: 'Pricing',
      nav_signout: 'Sign out',
      nav_signin: 'Sign in',
      nav_get_started: 'Get Started',
      footer_copy: '\u00A9 2026 Nuvo Math \u00B7 nuvostudio.club',
      footer_tagline: 'Algebra practice that actually teaches. Guided step-by-step practice and live tutoring for grades 6\u20139.',
      loading_just_moment: 'Just a moment!',

      // === login.html ===
      login_label: 'Student Login',
      login_heading: 'Welcome back',
      login_sub: 'Enter your student ID to continue',
      login_id_label: 'Student ID',
      login_id_placeholder: 'e.g. sofia',
      login_submit: 'Sign in \u2192',
      login_error_notfound: 'Student ID not found \u2014 check with your teacher',
      login_no_account: "Don't have an account?",
      login_trial_link: 'Start your free trial \u2192',
      login_signing_in: 'Signing in\u2026',
      login_error_generic: 'Something went wrong. Please try again.',
      login_error_network: 'Network error. Check your connection and try again.',

      // === home.html ===
      welcome_back: 'Welcome back,',
      curriculum_loading: 'Loading your curriculum\u2026',
      section_your_curriculum: 'Your curriculum',
      unit_label: 'Unit',
      level_label: 'Level',
      home_help_link: 'Need help? Ask Ronel',
      home_session_note: 'Your next session: check WhatsApp for scheduling',
      home_offline: 'Offline \u2014 check your connection',
      trial_expired_heading: 'Your free trial has ended',
      trial_expired_body: "You're one step away from full access. Choose a plan to keep practicing.",
      trial_expired_note: 'Questions? Email tutor@nuvostudio.club or WhatsApp 6014-1676.',
      trial_practice_btn: 'Practice \u2014 $29/month',
      trial_tutoring_btn: 'Practice + Tutoring \u2014 $99/month',

      // === lesson.html ===
      back_to_curriculum: '\u2190 Back to curriculum',
      loading_lesson_h2: 'Loading lesson\u2026',
      error_missing_params_h2: 'Missing lesson parameters',
      error_missing_params_p: 'This page requires <code>curriculum</code>, <code>unit</code>, and <code>stage</code> URL parameters.',
      error_lesson_not_found_h2: 'Lesson not found',
      error_load_failed_h2: "Couldn\u2019t load lesson",
      error_load_failed_p: 'Check your internet connection and try refreshing.',
      phase_intro: 'Intro',
      phase_concepts: 'Concepts',
      phase_example: 'Example',
      phase_practice: 'Practice',
      phase_test: 'Test',
      cover_begin_btn: 'Begin Lesson \u2192',
      concepts_card_title: 'Key Concepts',
      concepts_no_rules: 'No rules listed.',
      concepts_next_btn: 'Got it \u2014 show me an example \u2192',
      example_card_title: 'Worked Example',
      example_tab_symbolic: 'Symbolic',
      example_tab_visual: 'Visual',
      example_narration_init: 'Follow along \u2014 tap the button below to step through the example.',
      example_btn_show_step_n: 'Show step {n}',
      example_btn_goto_practice: 'Go to Practice \u2192',
      example_btn_try_yourself: 'Try it yourself \u2192',
      practice_tag: 'Practice',
      practice_subtitle: 'Work through these practice problems. Hints are available.',
      test_tag: 'Level Test',
      test_subtitle: 'Answer all questions. No hints this time!',
      result_complete: 'Complete!',
      result_level_complete: 'Level complete!',
      result_great_work: 'Great work \u2014 the next level is now unlocked.',
      result_score_correct: 'You got {score} of {total} correct.',
      result_back_btn: 'Back to curriculum \u2192',
      result_fail_h2: 'Keep Practicing!',
      result_fail_review: 'Review the example again and try the test once more.',
      result_fail_btn: 'Review example \u2192',

      // === dashboard.html ===
      loading_problems_h2: 'Loading your problems\u2026',
      error_no_student_h2: 'No student ID found',
      error_no_student_p: "Make sure you opened the right link. Ask your teacher if you're not sure!",
      error_student_notfound_h2: 'Student not found',
      error_student_notfound_p: "We couldn\u2019t find a student with the ID {id}. Check your link or ask your teacher.",
      error_load_problems_h2: "Couldn\u2019t load your problems",
      error_load_problems_p: 'Check your internet connection and try refreshing the page.',
      dashboard_hi: 'Hi,',
      dashboard_problems_label: 'Problems completed',
      dashboard_no_problems: 'No problems assigned yet.',
      dashboard_all_done: "Amazing \u2014 you've finished everything! \uD83C\uDF89",
      dashboard_get_started: 'Tap a problem below to get started!',
      dashboard_keep_going: 'Keep going \u2014 {n} left to go!',
      dashboard_completed: 'Completed',
      dashboard_not_started: 'Not started',
      dashboard_practice_again: 'Practice again \u2192',
      dashboard_your_problems: 'Your Problems',
      dashboard_all_done_banner: "You've finished all your problems \u2014 brilliant work!",
      dashboard_generating: 'Generating\u2026',
      dashboard_try_again: 'Try again',

      // === teacher.html ===
      teacher_login_h2: 'Teacher Login',
      teacher_login_p: 'Enter your teacher password to continue.',
      teacher_password_placeholder: 'Password',
      teacher_unlock_btn: 'Unlock',
      teacher_dashboard_h1: 'Teacher Dashboard',
      teacher_subtitle: 'Nuvo Studio',
      teacher_tab_students: 'Students & Homework',
      teacher_tab_problems: 'Problem Bank',
      teacher_all_students: 'ALL STUDENTS',
      teacher_loading: 'Loading\u2026',
      teacher_new_student_btn: '+ New Student',
      teacher_select_student: 'Select a student from the list to begin.',
      teacher_student_profile: 'Student Profile',
      teacher_edit_btn: 'Edit \u270F\uFE0F',
      teacher_edit_profile: 'Edit Profile',
      teacher_label_name: 'Name',
      teacher_label_student_id: 'Student ID',
      teacher_label_curriculum: 'Curriculum',
      teacher_label_grade: 'Grade / Stage',
      teacher_label_trial: 'Trial expiry',
      teacher_optional: '(optional)',
      teacher_auto_generated: '(auto-generated)',
      teacher_calc_hint: '(tap Question or Answer first)',
      teacher_save_btn: 'Save',
      teacher_cancel_btn: 'Cancel',
      teacher_new_student_title: 'New Student',
      teacher_create_btn: 'Create Student',
      teacher_homework_title: 'Homework',
      teacher_homework_note: 'Assigned problems appear on the student\u2019s home screen under \u201CYour homework\u201D',
      teacher_no_homework: 'No homework assigned yet',
      teacher_assign_label: 'Assign from problem bank',
      teacher_problem_id_placeholder: 'Problem ID',
      teacher_assign_btn: 'Assign',
      teacher_oneoff_heading: 'Or create a one-off problem',
      teacher_question_label: 'Question',
      teacher_word_desc: 'Word description',
      teacher_answer_label: 'Answer',
      teacher_expected_answer: 'Expected answer',
      teacher_add_assign_btn: 'Add & assign',
      teacher_student_link_label: 'Student link:',
      teacher_copy_link_btn: 'Copy link',
      teacher_problems_title: 'Problems',
      teacher_add_to_bank_title: 'Add to Bank',
      teacher_unit_label: 'Unit',
      teacher_level_label: 'Level',
      teacher_problem_type_label: 'Problem Type',
      teacher_math_type_label: 'Math Type',
      teacher_calc_label: 'Calculator',
      teacher_hint_label_1: 'Hint 1',
      teacher_hint_label_2: 'Hint 2',
      teacher_hint_label_3: 'Hint 3',
      teacher_add_hints: 'Add hints \u25BE',
      teacher_hide_hints: 'Add hints \u25B4',
      teacher_pid_label: 'Problem ID',
      teacher_save_to_bank_btn: 'Save to bank',
      teacher_saved_to_bank: 'Saved to bank \u2713',
      teacher_no_problems: 'No problems yet.',
      teacher_pf_curriculum_grade: 'Curriculum & Grade',
      teacher_trial_expired_label: 'Expired',
      teacher_trial_days_left: '{n}d left',
      teacher_auth_error_empty: 'Please enter a password.',
      teacher_id_required: 'ID and name are required.',
      teacher_saving: 'Saving\u2026',
      teacher_creating: 'Creating\u2026',
      teacher_steps_show: 'Steps \u25BE',
      teacher_steps_hide: 'Steps \u25B4',
      teacher_no_attempts: 'No attempts yet.',
      teacher_loading_logs: 'Loading\u2026',
      teacher_failed_logs: 'Failed to load logs.',
      teacher_toast_select_student: 'Select a student first.',
      teacher_toast_enter_pid: 'Enter a problem ID.',
      teacher_toast_problem_notfound: 'Problem \u201C{pid}\u201D not found in bank.',
      teacher_toast_already_assigned: 'Already assigned.',
      teacher_toast_assigned: 'Problem assigned.',
      teacher_toast_enter_qna: 'Enter question and answer.',
      teacher_toast_oneoff_assigned: 'One-off problem assigned.',
      teacher_toast_link_copied: 'Link copied!',
      teacher_toast_fill_required: 'Please fill in all required fields.',
      teacher_toast_wrong_password: 'Wrong password.',
      teacher_toast_failed_save: 'Failed to save. Check connection.',
      teacher_toast_failed_create: 'Creation failed. Check connection.',
      teacher_toast_failed_homework: 'Failed to save homework. Check connection.',
      teacher_toast_failed_student: 'Failed to load student data.',
      teacher_toast_failed_students: 'Could not load students.',
      teacher_toast_failed_problems: 'Could not load problems.',
      hw_tag_diagnostic: 'Diagnostic',
      hw_tag_test: 'Test',
      hw_tag_oneoff: 'One-off',
      hw_tag_practice: 'Practice',
      filter_all: 'All',

      // === index.html ===
      hero_eyebrow: 'Cambridge Lower Secondary \u00B7 Grades 6\u20139',
      hero_headline: 'Master Algebra.<br>At Your Own Pace.',
      hero_sub: 'Step-by-step guided practice that builds real understanding \u2014 paired with live weekly tutoring so your student never gets stuck alone.',
      hero_cta_primary: 'Start Practicing',
      hero_cta_secondary: 'See How It Works',
      hero_signin_note: 'Already enrolled?',
      hero_signin_link: 'Sign in \u2192',
      problem_section_label: 'Why students struggle',
      problem_section_title: 'Sound familiar?',
      problem_1_h3: 'Nobody to ask for help',
      problem_1_p: "Your student gets stuck on homework and has no one to turn to. They wait until the next session \u2014 or worse, give up. Algebra doesn\u2019t pause for anyone.",
      problem_2_h3: 'AI tools just hand over the answer',
      problem_2_p: "Most apps show the solution without teaching the thinking. That\u2019s not learning \u2014 it\u2019s copying. Students miss the understanding behind each step.",
      problem_3_h3: "One weekly session isn\u2019t enough",
      problem_3_p: 'Private tutoring is valuable, but students need daily practice to build fluency. Without it, lessons don\u2019t stick between sessions.',
      how_section_label: 'How it works',
      how_section_title: 'Simple. Guided. Effective.',
      step_1_h3: 'Enroll online',
      step_1_p: 'Choose your plan and get immediate access to the full curriculum \u2014 no scheduling, no waiting.',
      step_2_h3: 'Practice with the Guided Practice Engine',
      step_2_p: 'The Guided Practice Engine walks through problems step by step, giving targeted hints when students are stuck \u2014 never just handing over the answer.',
      step_3_h3: 'Get tutored live',
      step_3_p: 'Weekly Google Meet sessions with a real teacher to review progress, answer harder questions, and keep momentum going.',
      curriculum_section_label: "What they'll learn",
      curriculum_section_title: 'A complete algebra foundation',
      curriculum_section_sub: 'Seven structured units covering the full Cambridge Lower Secondary algebra curriculum, built for grades 6\u20139.',
      curriculum_section_badge: 'Cambridge Lower Secondary aligned \u00B7 Grades 6\u20139',
      pricing_section_label: 'Plans',
      pricing_section_title: 'Simple, honest pricing',
      pricing_section_sub: 'No contracts, no upsells. Pick the plan that fits your student best.',
      plan_practice_name: 'Practice',
      plan_practice_f1: 'Full 7-unit curriculum',
      plan_practice_f2: 'Guided Practice Engine \u2014 step-by-step practice',
      plan_practice_f3: 'Unlimited problems',
      plan_practice_f4: 'Progress tracking dashboard',
      plan_practice_cta: 'Start Free Trial',
      plan_popular: 'Most Popular',
      plan_tutoring_name: 'Practice + Tutoring',
      plan_tutoring_f1: 'Everything in Practice',
      plan_tutoring_f2: '4 live sessions/month via Google Meet',
      plan_tutoring_f3: 'Personalized homework assignments',
      plan_tutoring_f4: 'Direct WhatsApp support',
      plan_tutoring_cta: 'Start Free Trial',
      pricing_note: 'No contracts. Cancel anytime.'
    },

    es: {
      // === SHARED NAV / FOOTER ===
      nav_how_it_works: 'C\u00F3mo funciona',
      nav_curriculum: 'Plan de estudios',
      nav_pricing: 'Precios',
      nav_signout: 'Cerrar sesi\u00F3n',
      nav_signin: 'Iniciar sesi\u00F3n',
      nav_get_started: 'Empezar',
      footer_copy: '\u00A9 2026 Nuvo Math \u00B7 nuvostudio.club',
      footer_tagline: 'Pr\u00E1ctica de \u00E1lgebra que realmente ense\u00F1a. Pr\u00E1ctica guiada paso a paso y tutor\u00EDas en vivo para grados 6\u20139.',
      loading_just_moment: '\u00A1Un momento!',

      // === login.html ===
      login_label: 'Acceso de Estudiante',
      login_heading: 'Bienvenido de nuevo',
      login_sub: 'Ingresa tu ID de estudiante para continuar',
      login_id_label: 'ID de estudiante',
      login_id_placeholder: 'ej. sofia',
      login_submit: 'Entrar \u2192',
      login_error_notfound: 'ID no encontrado \u2014 consulta a tu maestro',
      login_no_account: '\u00BFNo tienes cuenta?',
      login_trial_link: 'Comienza tu prueba gratuita \u2192',
      login_signing_in: 'Entrando\u2026',
      login_error_generic: 'Algo sali\u00F3 mal. Int\u00E9ntalo de nuevo.',
      login_error_network: 'Error de red. Verifica tu conexi\u00F3n e int\u00E9ntalo de nuevo.',

      // === home.html ===
      welcome_back: 'Hola de nuevo,',
      curriculum_loading: 'Cargando tu plan de estudios\u2026',
      section_your_curriculum: 'Tu plan de estudios',
      unit_label: 'Unidad',
      level_label: 'Nivel',
      home_help_link: '\u00BFNecesitas ayuda? Preg\u00FAntale a Ronel',
      home_session_note: 'Tu pr\u00F3xima sesi\u00F3n: revisa WhatsApp para coordinar',
      home_offline: 'Sin conexi\u00F3n \u2014 verifica tu red',
      trial_expired_heading: 'Tu prueba gratuita ha terminado',
      trial_expired_body: 'Est\u00E1s a un paso del acceso completo. Elige un plan para seguir practicando.',
      trial_expired_note: '\u00BFPreguntas? Esc\u00EDbenos a tutor@nuvostudio.club o por WhatsApp 6014-1676.',
      trial_practice_btn: 'Pr\u00E1ctica \u2014 $29/mes',
      trial_tutoring_btn: 'Pr\u00E1ctica + Tutor\u00EDa \u2014 $99/mes',

      // === lesson.html ===
      back_to_curriculum: '\u2190 Volver al plan de estudios',
      loading_lesson_h2: 'Cargando lecci\u00F3n\u2026',
      error_missing_params_h2: 'Par\u00E1metros de lecci\u00F3n faltantes',
      error_missing_params_p: 'Esta p\u00E1gina requiere los par\u00E1metros <code>curriculum</code>, <code>unit</code> y <code>stage</code> en la URL.',
      error_lesson_not_found_h2: 'Lecci\u00F3n no encontrada',
      error_load_failed_h2: 'No se pudo cargar la lecci\u00F3n',
      error_load_failed_p: 'Verifica tu conexi\u00F3n a internet y actualiza la p\u00E1gina.',
      phase_intro: 'Intro',
      phase_concepts: 'Conceptos',
      phase_example: 'Ejemplo',
      phase_practice: 'Pr\u00E1ctica',
      phase_test: 'Prueba',
      cover_begin_btn: 'Comenzar lecci\u00F3n \u2192',
      concepts_card_title: 'Conceptos clave',
      concepts_no_rules: 'No hay reglas listadas.',
      concepts_next_btn: 'Entendido \u2014 mu\u00E9strame un ejemplo \u2192',
      example_card_title: 'Ejemplo resuelto',
      example_tab_symbolic: 'Simb\u00F3lico',
      example_tab_visual: 'Visual',
      example_narration_init: 'Sigue el ejemplo \u2014 toca el bot\u00F3n de abajo para avanzar paso a paso.',
      example_btn_show_step_n: 'Mostrar paso {n}',
      example_btn_goto_practice: 'Ir a la pr\u00E1ctica \u2192',
      example_btn_try_yourself: 'Int\u00E9ntalo t\u00FA mismo \u2192',
      practice_tag: 'Pr\u00E1ctica',
      practice_subtitle: 'Resuelve estos problemas de pr\u00E1ctica. Hay pistas disponibles.',
      test_tag: 'Prueba de nivel',
      test_subtitle: '\u00A1Responde todas las preguntas. Sin pistas esta vez!',
      result_complete: '\u00A1Completado!',
      result_level_complete: '\u00A1Nivel completado!',
      result_great_work: '\u00A1Buen trabajo! El siguiente nivel est\u00E1 desbloqueado.',
      result_score_correct: 'Obtuviste {score} de {total} correctas.',
      result_back_btn: 'Volver al plan de estudios \u2192',
      result_fail_h2: '\u00A1Sigue practicando!',
      result_fail_review: 'Revisa el ejemplo de nuevo e intenta la prueba una vez m\u00E1s.',
      result_fail_btn: 'Revisar el ejemplo \u2192',

      // === dashboard.html ===
      loading_problems_h2: 'Cargando tus problemas\u2026',
      error_no_student_h2: 'ID de estudiante no encontrado',
      error_no_student_p: 'As\u00E9g\u00FArate de haber abierto el enlace correcto. \u00A1Consulta a tu maestro si no est\u00E1s seguro!',
      error_student_notfound_h2: 'Estudiante no encontrado',
      error_student_notfound_p: 'No encontramos un estudiante con el ID {id}. Verifica tu enlace o consulta a tu maestro.',
      error_load_problems_h2: 'No se pudieron cargar tus problemas',
      error_load_problems_p: 'Verifica tu conexi\u00F3n a internet y actualiza la p\u00E1gina.',
      dashboard_hi: '¡Hola,',
      dashboard_problems_label: 'Problemas completados',
      dashboard_no_problems: 'A\u00FAn no hay problemas asignados.',
      dashboard_all_done: '\u00A1Incre\u00EDble \u2014 terminaste todo! \uD83C\uDF89',
      dashboard_get_started: '\u00A1Toca un problema para comenzar!',
      dashboard_keep_going: '\u00A1Sigue adelante \u2014 te quedan {n}!',
      dashboard_completed: 'Completado',
      dashboard_not_started: 'Sin comenzar',
      dashboard_practice_again: 'Practicar de nuevo \u2192',
      dashboard_your_problems: 'Tus problemas',
      dashboard_all_done_banner: '\u00A1Terminaste todos tus problemas \u2014 excelente trabajo!',
      dashboard_generating: 'Generando\u2026',
      dashboard_try_again: 'Intentar de nuevo',

      // === teacher.html ===
      teacher_login_h2: 'Acceso de Maestro',
      teacher_login_p: 'Ingresa tu contrase\u00F1a de maestro para continuar.',
      teacher_password_placeholder: 'Contrase\u00F1a',
      teacher_unlock_btn: 'Desbloquear',
      teacher_dashboard_h1: 'Panel del Maestro',
      teacher_subtitle: 'Nuvo Studio',
      teacher_tab_students: 'Estudiantes y Tareas',
      teacher_tab_problems: 'Banco de Problemas',
      teacher_all_students: 'TODOS LOS ESTUDIANTES',
      teacher_loading: 'Cargando\u2026',
      teacher_new_student_btn: '+ Nuevo Estudiante',
      teacher_select_student: 'Selecciona un estudiante de la lista para comenzar.',
      teacher_student_profile: 'Perfil del Estudiante',
      teacher_edit_btn: 'Editar \u270F\uFE0F',
      teacher_edit_profile: 'Editar Perfil',
      teacher_label_name: 'Nombre',
      teacher_label_student_id: 'ID de Estudiante',
      teacher_label_curriculum: 'Plan de Estudios',
      teacher_label_grade: 'Grado / Etapa',
      teacher_label_trial: 'Vencimiento de prueba',
      teacher_optional: '(opcional)',
      teacher_auto_generated: '(generado autom\u00E1ticamente)',
      teacher_calc_hint: '(toca Pregunta o Respuesta primero)',
      teacher_save_btn: 'Guardar',
      teacher_cancel_btn: 'Cancelar',
      teacher_new_student_title: 'Nuevo Estudiante',
      teacher_create_btn: 'Crear Estudiante',
      teacher_homework_title: 'Tarea',
      teacher_homework_note: 'Los problemas asignados aparecen en la pantalla de inicio del estudiante bajo \u201CTu tarea\u201D',
      teacher_no_homework: 'A\u00FAn no hay tarea asignada',
      teacher_assign_label: 'Asignar desde el banco de problemas',
      teacher_problem_id_placeholder: 'ID del Problema',
      teacher_assign_btn: 'Asignar',
      teacher_oneoff_heading: 'O crea un problema \u00FAnico',
      teacher_question_label: 'Pregunta',
      teacher_word_desc: 'Descripci\u00F3n en palabras',
      teacher_answer_label: 'Respuesta',
      teacher_expected_answer: 'Respuesta esperada',
      teacher_add_assign_btn: 'Agregar y asignar',
      teacher_student_link_label: 'Enlace del estudiante:',
      teacher_copy_link_btn: 'Copiar enlace',
      teacher_problems_title: 'Problemas',
      teacher_add_to_bank_title: 'Agregar al Banco',
      teacher_unit_label: 'Unidad',
      teacher_level_label: 'Nivel',
      teacher_problem_type_label: 'Tipo de Problema',
      teacher_math_type_label: 'Tipo de Matem\u00E1ticas',
      teacher_calc_label: 'Calculadora',
      teacher_hint_label_1: 'Pista 1',
      teacher_hint_label_2: 'Pista 2',
      teacher_hint_label_3: 'Pista 3',
      teacher_add_hints: 'Agregar pistas \u25BE',
      teacher_hide_hints: 'Agregar pistas \u25B4',
      teacher_pid_label: 'ID del Problema',
      teacher_save_to_bank_btn: 'Guardar en el banco',
      teacher_saved_to_bank: 'Guardado en el banco \u2713',
      teacher_no_problems: 'Sin problemas a\u00FAn.',
      teacher_pf_curriculum_grade: 'Plan de Estudios y Grado',
      teacher_trial_expired_label: 'Vencido',
      teacher_trial_days_left: '{n}d restantes',
      teacher_auth_error_empty: 'Por favor ingresa una contrase\u00F1a.',
      teacher_id_required: 'El ID y el nombre son requeridos.',
      teacher_saving: 'Guardando\u2026',
      teacher_creating: 'Creando\u2026',
      teacher_steps_show: 'Pasos \u25BE',
      teacher_steps_hide: 'Pasos \u25B4',
      teacher_no_attempts: 'Sin intentos a\u00FAn.',
      teacher_loading_logs: 'Cargando\u2026',
      teacher_failed_logs: 'Error al cargar los registros.',
      teacher_toast_select_student: 'Selecciona un estudiante primero.',
      teacher_toast_enter_pid: 'Ingresa un ID de problema.',
      teacher_toast_problem_notfound: 'Problema \u201C{pid}\u201D no encontrado en el banco.',
      teacher_toast_already_assigned: 'Ya asignado.',
      teacher_toast_assigned: 'Problema asignado.',
      teacher_toast_enter_qna: 'Ingresa la pregunta y la respuesta.',
      teacher_toast_oneoff_assigned: 'Problema \u00FAnico asignado.',
      teacher_toast_link_copied: '\u00A1Enlace copiado!',
      teacher_toast_fill_required: 'Por favor completa todos los campos requeridos.',
      teacher_toast_wrong_password: 'Contrase\u00F1a incorrecta.',
      teacher_toast_failed_save: 'Error al guardar. Verifica tu conexi\u00F3n.',
      teacher_toast_failed_create: 'Error al crear. Verifica tu conexi\u00F3n.',
      teacher_toast_failed_homework: 'Error al guardar la tarea. Verifica tu conexi\u00F3n.',
      teacher_toast_failed_student: 'Error al cargar los datos del estudiante.',
      teacher_toast_failed_students: 'No se pudo cargar la lista de estudiantes.',
      teacher_toast_failed_problems: 'No se pudo cargar los problemas.',
      hw_tag_diagnostic: 'Diagn\u00F3stico',
      hw_tag_test: 'Prueba',
      hw_tag_oneoff: '\u00DAnico',
      hw_tag_practice: 'Pr\u00E1ctica',
      filter_all: 'Todos',

      // === index.html ===
      hero_eyebrow: 'Cambridge Lower Secondary \u00B7 Grados 6\u20139',
      hero_headline: 'Domina el \u00C1lgebra.<br>A tu propio ritmo.',
      hero_sub: 'Pr\u00E1ctica guiada paso a paso que construye comprensi\u00F3n real \u2014 combinada con tutor\u00EDas semanales en vivo para que tu estudiante nunca se quede atascado.',
      hero_cta_primary: 'Empezar a practicar',
      hero_cta_secondary: 'Ver c\u00F3mo funciona',
      hero_signin_note: '\u00BFYa inscrito?',
      hero_signin_link: 'Iniciar sesi\u00F3n \u2192',
      problem_section_label: 'Por qu\u00E9 los estudiantes tienen dificultades',
      problem_section_title: '\u00BFTe suena familiar?',
      problem_1_h3: 'Nadie a quien pedir ayuda',
      problem_1_p: 'Tu estudiante se queda atascado en la tarea y no tiene a quien recurrir. Espera hasta la pr\u00F3xima sesi\u00F3n \u2014 o peor, se rinde. El \u00E1lgebra no espera por nadie.',
      problem_2_h3: 'Las herramientas de IA simplemente dan la respuesta',
      problem_2_p: 'La mayor\u00EDa de las apps muestran la soluci\u00F3n sin ense\u00F1ar el razonamiento. Eso no es aprender \u2014 es copiar. Los estudiantes pierden la comprensi\u00F3n detr\u00E1s de cada paso.',
      problem_3_h3: 'Una sesi\u00F3n semanal no es suficiente',
      problem_3_p: 'La tutor\u00EDa privada es valiosa, pero los estudiantes necesitan pr\u00E1ctica diaria para desarrollar fluidez. Sin ella, las clases no se retienen entre sesiones.',
      how_section_label: 'C\u00F3mo funciona',
      how_section_title: 'Simple. Guiado. Efectivo.',
      step_1_h3: 'Inscr\u00EDbete en l\u00EDnea',
      step_1_p: 'Elige tu plan y obt\u00E9n acceso inmediato al plan de estudios completo \u2014 sin programar, sin esperar.',
      step_2_h3: 'Practica con el Motor de Pr\u00E1ctica Guiada',
      step_2_p: 'El Motor de Pr\u00E1ctica Guiada recorre los problemas paso a paso, dando pistas precisas cuando los estudiantes se quedan atascados \u2014 sin simplemente dar la respuesta.',
      step_3_h3: 'Recibe tutor\u00EDa en vivo',
      step_3_p: 'Sesiones semanales por Google Meet con un maestro real para revisar el progreso, responder preguntas m\u00E1s dif\u00EDciles y mantener el impulso.',
      curriculum_section_label: 'Lo que aprender\u00E1n',
      curriculum_section_title: 'Una base completa de \u00E1lgebra',
      curriculum_section_sub: 'Siete unidades estructuradas que cubren el plan de estudios completo de \u00E1lgebra Cambridge Lower Secondary, para grados 6\u20139.',
      curriculum_section_badge: 'Cambridge Lower Secondary \u00B7 Grados 6\u20139',
      pricing_section_label: 'Planes',
      pricing_section_title: 'Precios simples y transparentes',
      pricing_section_sub: 'Sin contratos, sin extras. Elige el plan que mejor se adapte a tu estudiante.',
      plan_practice_name: 'Pr\u00E1ctica',
      plan_practice_f1: 'Plan de estudios completo de 7 unidades',
      plan_practice_f2: 'Motor de Pr\u00E1ctica Guiada \u2014 pr\u00E1ctica paso a paso',
      plan_practice_f3: 'Problemas ilimitados',
      plan_practice_f4: 'Panel de seguimiento de progreso',
      plan_practice_cta: 'Comenzar Prueba Gratuita',
      plan_popular: 'M\u00E1s Popular',
      plan_tutoring_name: 'Pr\u00E1ctica + Tutor\u00EDa',
      plan_tutoring_f1: 'Todo en Pr\u00E1ctica',
      plan_tutoring_f2: '4 sesiones en vivo/mes por Google Meet',
      plan_tutoring_f3: 'Tareas personalizadas',
      plan_tutoring_f4: 'Soporte directo por WhatsApp',
      plan_tutoring_cta: 'Comenzar Prueba Gratuita',
      pricing_note: 'Sin contratos. Cancela cuando quieras.'
    }
  };

  var _lang = (navigator.language || '').startsWith('es') ? 'es' : 'en';

  window.Lang = {
    detect: function () { return _lang; },

    t: function (key) {
      return (STRINGS[_lang] || {})[key] || STRINGS.en[key] || key;
    },

    apply: function () {
      // textContent translations
      document.querySelectorAll('[data-i18n]').forEach(function (el) {
        el.textContent = window.Lang.t(el.getAttribute('data-i18n'));
      });
      // innerHTML translations (for strings containing HTML like <br>, <code>)
      document.querySelectorAll('[data-i18n-html]').forEach(function (el) {
        el.innerHTML = window.Lang.t(el.getAttribute('data-i18n-html'));
      });
      // placeholder translations
      document.querySelectorAll('[data-i18n-placeholder]').forEach(function (el) {
        el.placeholder = window.Lang.t(el.getAttribute('data-i18n-placeholder'));
      });
      // aria-label translations
      document.querySelectorAll('[data-i18n-aria-label]').forEach(function (el) {
        el.setAttribute('aria-label', window.Lang.t(el.getAttribute('data-i18n-aria-label')));
      });
    }
  };
}());
